# This file is used for Gradle options, for the rest use stonecutter.properties.toml
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Required by ForgeGradle 7 to merge the mod source sets for dev runs (see the Forge MDK)
net.minecraftforge.gradle.merge-source-sets=true
