# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "itemframesplus"
mod.name = "ItemFrames+"
mod.group = "com.kryp"
mod.version = "1.2.0"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"

["1.16.5"]

[fabric."1.16.5"]
mod.mc_compat = ">=1.16.5 <1.19"
deps.fabric_api = "0.42.0+1.16"
deps.fabric_command_api = "fabric-command-api-v1"
pack_format = 6

["1.18"]

[forge."1.18"]
mod.mc_compat = "=1.18"
deps.forge_loader = "38.0.17"
deps.forge_fml = "38"
pack_format = 8

["1.18.1"]

[forge."1.18.1"]
mod.mc_compat = "=1.18.1"
deps.forge_loader = "39.1.2"
deps.forge_fml = "39"
pack_format = 8

["1.19"]

[fabric."1.19"]
mod.mc_compat = ">=1.19 <1.20.5"
deps.fabric_api = "0.58.0+1.19"
deps.fabric_command_api = "fabric-command-api-v2"
pack_format = 9

["1.20.5"]

[fabric."1.20.5"]
mod.mc_compat = ">=1.20.5 <1.21"
deps.fabric_api = "0.97.8+1.20.5"
deps.fabric_command_api = "fabric-command-api-v2"
pack_format = 32

["1.21"]

[fabric."1.21"]
mod.mc_compat = ">=1.21 <1.21.4"
deps.fabric_api = "0.100.8+1.21"
deps.fabric_command_api = "fabric-command-api-v2"
pack_format = 34

["1.21.4"]

[fabric."1.21.4"]
mod.mc_compat = ">=1.21.4 <1.21.9"
deps.fabric_api = "0.110.5+1.21.4"
deps.fabric_command_api = "fabric-command-api-v2"
pack_format = 46

["1.21.9"]

[fabric."1.21.9"]
mod.mc_compat = ">=1.21.9 <26.1"
deps.fabric_api = "0.141.6+1.21.11"
deps.fabric_command_api = "fabric-command-api-v2"
pack_format = 69

["26.1"]

[fabric."26.1"]
mod.mc_compat = ">=26.1 <26.2"
deps.fabric_api = "0.145.1+26.1"
deps.fabric_command_api = "fabric-command-api-v2"
pack_format = 84

["26.2"]

[fabric."26.2"]
mod.mc_compat = ">=26.2"
deps.fabric_api = "0.156.0+26.2"
deps.fabric_command_api = "fabric-command-api-v2"
pack_format = 88
